### ISSUE TITLE
Suppress some events which spam launch.log

### ISSUE THREAD

**Issue by Dragon-32** [X2CommunityCore/X2WOTCCommunityHighlander#479] opened 2019-04-13 18:14 UTC
In a heavily modded game (hello) approximately half of the events recorded in launch.log are of the format:

Error: (AddNetObject) Object `<String>` with invalid NetIndex `<Number>` (max: `<Number>`)
or
Error: (RemoveNetObject) Object `<String>` with invalid NetIndex `<Number>` (max: `<Number>`)

There're also the plurals:
Error: (AddNetObject) Objects `<String>` and `<String>` have duplicate NetIndex `<Number>`
or
Error: (RemoveNetObject) Objects `<String>` and `<String>` have duplicate NetIndex `<Number>`

Finding important errors in launch.log is already hard enough, if there was some way to suppress these errors from being written (Do these events have unique IDs? Would it need a regular expression?) then debugging heavily modded games would be easier, IMO.

There're also "Warning: Warning, Failed to load..." errors but I think some which start that relate to missing FX packages, so they're probably worth leaving alone.

**Comment by yoshimo** [comment] 2019-04-13 18:47
Well instead of just not printing them, maybe it is better to fix the underlying cause.

**Comment by robojumper** [comment] 2019-04-13 20:53
The only way to suppress those is suppressing the `Error` tag, which suppresses way more than we want. Also, they originate from native code and I have no idea what the problem is :(

**Comment by Dragon-32** [comment] 2019-04-13 23:28
Well bugger.

**Comment by Iridar** [comment] 2023-08-15 05:57
Seeing as there's probably nothing that we can do about it, I'll be closing this. I do want to mention that I *suspect* that at least some of the NetObject errors happen when mod(s) use an asset name that already exists in other packages, be it other mods or the game itself. Pure speculation, though.

**Closed by Iridar** 2023-08-15 05:57 UTC
Labels: bug-basegame
