### ISSUE TITLE
Linux version do not start and hang crashes file with Musashi-' Primary Secondaries mod.

### ISSUE THREAD

**Issue by f-abel** [X2CommunityCore/X2WOTCCommunityHighlander#336] opened 2018-11-12 20:25 UTC
I tried to make a clean testbed : 
unsuscribed highlander
resuscribed highlander and waited for end of download 
used highlander WOTC for win/Mac/Lin V1.16.0 as per the release note
suscribed to Primary Secondary
Start and enable Primary Secondary, 
highlander was already enabled by previous install
Wait for the crash to apear
Wait for the message application do not respond kill ?
kill and get the file : 
[3f35a70a-cf00-665b-1469fe79-7b750a38.dmp.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/2573490/3f35a70a-cf00-665b-1469fe79-7b750a38.dmp.zip)

for record my system info :
Computer Information:
Manufacturer: Unknown
Model: Unknown
Form Factor: Desktop
No Touch Input Detected

Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
CPU Family: 0x6
CPU Model: 0x9e
CPU Stepping: 0xa
CPU Type: 0x0
Speed: 4700 Mhz
12 logical processors
6 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

Operating System Version:
Ubuntu 18.04.1 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 4.15.0-38-generic
X Server Vendor: The X.Org Foundation
X Server Release: 11906000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime-beta-release_2018-10-24

Video Card:
Driver: NVIDIA Corporation GeForce GTX 1070/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 390.87
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1b81
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.91" x 11.77" (23.98" diag)
53.1cm x 29.9cm (60.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 8192 MB
Supported MSAA Modes: 2x 4x 8x 16x 

Sound card:
Audio device: Realtek ALC887-VD

Memory:
RAM: 15970 Mb

Miscellaneous:
UI Language: English
LANG: fr_CA.UTF-8
Total Hard Disk Space Available: 449649 Mb
Largest Free Hard Disk Block: 291299 Mb
VR Headset: None detected

Recent Failure Reports:

**Comment by robojumper** [comment] 2018-11-12 20:43
Hi,

sorry to hear you are having issues. To clarify, am I interpreting your report right in that the Highlander does not crash when enabled without Primary Secondaries, and the game starts crashing as soon as Primary Secondaries is enabled? If so, there are two things you could do:

* Send us the `Launch.log` file from `~/.local/share/feral-interactive/XCOM 2 WotC/VFS/Local/my games/XCOM2 War of the Chosen/XComGame/Logs/`
* Try running Primary Secondaries without the Highlander (for testing purposes).

**Comment by robojumper** [comment] 2018-11-14 22:16
It seems that the Highlander isn't at fault then, and the Linux game somehow fails to load a package from Primary Secondaries. Closing, but feel free to re-open if you have further insight -- even if the issue isn't caused by the Highlander, it's still of interest to us.

**Closed by robojumper** 2018-11-14 22:16 UTC
