### ISSUE TITLE
Units still stunned on tactical end have no action points on next mission

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#824] opened 2020-03-27 10:38 UTC
The base game does not clear the stunned action points of any units that are still stunned when a tactical game ends, which leads to them having 0 action points at the start of the next mission they go on.

**Comment by pledbrook** [comment] 2020-03-27 10:46
We need to clear the `StunnedActionPoints` and `StunnedThisTurn` variables on `XComGameState_Unit` at the end of the tactical mission. I see a couple of options for that:

1. In `XComGameState_Unit.OnEndTacticalPlay()`
2. In `X2Effect_Stunned.UnitEndedTacticalPlay()`

Long War 2 plumped for the second, but I don't really know the relative merits of the two. Any thoughts? I lean towards adding the behaviour directly to `XCGS_Unit` since it's that class's properties that need to be cleared.

**Comment by pledbrook** [comment] 2020-03-27 10:49
This is the LWOTC save file I'm using to reproduce the bug:

[save_BUGs Stun, Revival and Sabotage.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/4392903/save_BUGs.Stun.Revival.and.Sabotage.zip)

The drone just needs to be killed and the C4 set before ending the mission. I've gone with a LWOTC save because it's much easier to set up.

**Comment by Xymanek** [comment] 2020-03-27 14:53
> I've gone with a LWOTC save because it's much easier to set up.

But not for everyone else to check 😂 

> I lean towards adding the behaviour directly to `XCGS_Unit` since it's that class's properties that need to be cleared.

I support this notion

**Comment by Iridar** [comment] 2020-09-02 15:47
> We need to clear the `StunnedActionPoints` and `StunnedThisTurn` variables on `XComGameState_Unit` at the end of the tactical mission. I see a couple of options for that:
> 
> 1. In `XComGameState_Unit.OnEndTacticalPlay()`
> 2. In `X2Effect_Stunned.UnitEndedTacticalPlay()`
> 
> Long War 2 plumped for the second, but I don't really know the relative merits of the two. Any thoughts? I lean towards adding the behaviour directly to `XCGS_Unit` since it's that class's properties that need to be cleared.

The merits are that in the first case, the bug is fixed globally, while in the second case only for that specific stun effect. I don't recall seeing abilities that would apply stun via means other than `X2Effect_Stunned`, but it's absolutely possible, and would cause the unit to bug out if the bug is fixed only in the `X2Effect_Stunned`. As such, I agree that the bug should be fixed in XCGS_Unit globally. 

I'm guessing LW2 opted to fix it locally to keep changes isolated, or maybe the other solution just did not occur to them. You could say the bug is caused by X2Effect_Stunned, would make sense to fix it there as well.

**Closed** 2020-10-22 16:44 UTC
Labels: bug-basegame
