### ISSUE TITLE
Default weapon colors: I-have-no-idea-why edition.

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2WOTCCommunityHighlander#343] opened 2018-11-17 00:24 UTC
WotC made this change: 
```diff
	//For generated soldiers, weapon tint now defaults to no tint
-	kSoldier.kAppearance.iWeaponTint = -1;
+	kSoldier.kAppearance.iWeaponTint = 20;
```

which preserves the default color for conventional weapons, but changes up the default colors for all other weapons a ton. Why? Material changes?

------------------------------------------------

Somewhat related: DerBK pointed out that all enemy weapons that can be tinted have a green tint (IIRC this was even a problem for LW2 ADVENT gunners):

![image](https://cdn.discordapp.com/attachments/361218721626456064/513097071679504384/20181116220040_1.jpg)

This is because the default weapon color in the **character** appearance is `0` (green). In `ApplyInventoryLoadout`, this gets copied over to the weapon. A Highlander change could apply a heuristic that changes this for non-soldiers to `INDEX_NONE` (or 20 😛 ).

**Comment by Iridar** [comment] 2020-11-15 08:21
Should this issue be closed? Or does it remain open because it needs docs?

**Comment by Iridar** [comment] 2020-11-15 22:42
The PR pertaining to this issue has been merged, so the issue is resolved, so I'm closing it. It still needs docs, though.

**Closed by Iridar** 2020-11-15 22:42 UTC
Labels: enhancement, needs-docs
