### ISSUE TITLE
MoveClimbWall function inclusion

### ISSUE THREAD

**Issue by StopFlaggingMe** [X2CommunityCore/X2WOTCCommunityHighlander#715] opened 2019-12-31 01:53 UTC
I am requesting an update to include the X2Action_MoveClimbWall function. This way the various mods that use it won't through a conflict. To find the desired source code, sample include:
steamcommunity.com/sharedfiles/filedetails/?id=1918499687 [WOTC] The Hive
steamcommunity.com/sharedfiles/filedetails/?id=1129661000 [WotC] The MOCX Initiative
steamcommunity.com/sharedfiles/filedetails/?id=1126623381 A Better ADVENT: War of the Chosen
steamcommunity.com/sharedfiles/filedetails/?id=1561030099 Mitzruti Perk Pack

This way mod authors don't have to be trusted when they say 'my mod's conflict with x' is fine, since they can update to no longer conflict. Thanks!

**Comment by Xymanek** [comment] 2019-12-31 08:01
A Better ADVENT and Mitzruti Perk Pack do not depend on the CHL and thus cannot make use of this, even if it's included. Additionally, If we include it in the CHL but ABA (or some other mod) still ships with it, ABA's version will take priority over CHL

> mod authors don't have to be trusted when they say 'my mod's conflict with x' is fine

Personally I would trust that more than "No conflicts" since it means that the mod author investigated the report and confirmed it to be a non-issue

**Comment by Iridar** [comment] 2019-12-31 08:07
The way X2Action_MoveClimbWall override is used, there is no actual conflict. It's a false flag by AML. Sp this should be fixed on the side of the AML instead.

**Comment by Xymanek** [comment] 2019-12-31 08:09
AML issue on this matter: https://github.com/X2CommunityCore/xcom2-launcher/issues/148

**Comment by Iridar** [comment] 2021-01-12 19:02
That said, is there a particular reason *not* to include this file into CHL? It will not interfere with mods that already MCO it, and spare the need for any future mods that depend on CHL anyway from having to MCO it.

**Comment by Xymanek** [comment] 2021-02-14 09:55
Mods which do not depend on CHL will not be able to rely on the modified file being included in CHL.

As such, including this file into CHL can cause confusion over whether the change comes from CHL or from a mod that uses the change but doesn't require CHL (and thus uses the standalone MCO)

**Comment by Iridar** [comment] 2023-09-18 10:05
This was addressed in AML, closing.

**Closed by Iridar** 2023-09-18 10:05 UTC
