### ISSUE TITLE
Events during campaign setup are "lost" regarding listener templates

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/X2WOTCCommunityHighlander#869] opened 2020-05-22 14:38 UTC
When a campaign is first launched, the initial set of state creation is done in the shell map. Shell has no listener templates (see #297) and as such, mods cannot react to the events (hooks) triggered during that phase. Below are the events that get triggered when using just CHL (based on CI's latest development version, 3c3bdd565e9bef45e0f261ac74f33b7fe0257bf8):

```
UnitRandomizedStats
OverrideClipSize
OverrideRandomizeAppearance
OverrideHasHeavyWeapon
OverrideItemMinEquipped
OverrideHasGrenadePocket
NewCrewNotification
UnitRankUp
OverrideAddChosenTacticalTagsToMission
OverrideScienceScore
OverrideCurrentDoom
SquaddieItemStateApplied
```

Source behind generating this list: 5fc965c20a3fc7eaace430c37faffcda5833b4b6
Full output + parser: https://gist.github.com/Xymanek/b8ac7021900d17ba417d2f7759151525
Note that the list above potentially does not include all events triggered, in case some events are triggered in response to other events (I had to practically disable all listeners to investigate)

An easy solution would be to register strategy listener templates before starting the process, since these are mostly strategy events. Downside is that the listeners might not expect to be called in not-ready-campaign state and might not expect to be called while a start state is opened.

An opt-in solution would be adding `RegisterInStrategySetup` to `CHEventListenerTemplate`; obviously that would require mod authors to manually mark their listeners, so some bugs resulting from the above behaviour might remain.

cc @Musashi1584 @pledbrook since I know some of these events are yours

**Comment by Musashi1584** [comment] 2020-05-27 10:47
i support the RegisterInStrategySetup solution since its the probably the most bc friendly way and would be consistent with the current implementation of register in strategy and register in tactical.
afaik the current limitation did not had any negative consequences on the events i created and used (at least i haven't actively encountered any bugs caused by this). Anyhow i think this is something that can be relevant for certain events and it should be addressed in any solution space of  #297

**Closed** 2021-02-07 13:12 UTC
