### ISSUE TITLE
Suggestion - Integrate Rename And Reorganize Campaign mod

### ISSUE THREAD

**Issue by korgano** [X2CommunityCore/X2WOTCCommunityHighlander#59] opened 2017-10-04 14:59 UTC
Not sure if @bountygiver is already going to do this/suggest doing this, but integrating save management features into the highlander would be ideal, since this overrides multiple classes (UISaveGame, UILoadGame, UISaveLoadGameListItem) and provides a great deal of functionality. It would also hopefully prevent issues with the configurable tactical save amounts.

[[WOTC] Rename and Reorganize Campaign](http://steamcommunity.com/sharedfiles/filedetails/?id=1157270927)

**Comment by bountygiver** [comment] 2017-10-04 16:43
No, rolling this into highlander can cause more problems than it solve, the multiple class override is a non issue here as these classes are closely related so there's close to no reason to override one and not the other. One thing that merging this into highlander is a bad idea is due to how much this mod changes these screen so it will work completely different from vanilla, causing any mods that tries to override this to have unexpected behaviour unless compiled against highlander, and if such incompability cannot be solved might as well make it more clear with a direct override.

The only part that should be merged into highlander is the quicksort algorithm.

**Closed** 2017-10-05 07:34 UTC
Labels: wontfix
