### ISSUE TITLE
Class selection for GTS Rookie training is not showing

### ISSUE THREAD

**Issue by pledbrook** [X2CommunityCore/X2WOTCCommunityHighlander#630] opened 2019-09-23 09:09 UTC
When a rookie is selected for training in the GTS, the class selection screen doesn't appear when using the current published beta highlander.

To reproduce, load the following save file and just attempt to train a rookie in the GTS:

[save_Beta Highlander Bug.zip](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/files/3641368/save_Beta.Highlander.Bug.zip)

**Comment by Iridar** [comment] 2021-01-12 01:59
I couldn't reproduce this bug with the *current* master branch of the Highlander, neither on my own, nor with your save. I assume this Issue is no longer relevant. Closing.

**Closed by Iridar** 2021-01-12 01:59 UTC
Labels: bug-highlander
