### ISSUE TITLE
Allow checking `XCGS_Item::GetWeaponCategory()` in addition to existing checks

### ISSUE THREAD

**Issue by E3245** [X2CommunityCore/X2WOTCCommunityHighlander#1261] opened 2023-09-29 06:44 UTC
Certain paths in the code check either the weapon template's `WeaponCat` or the value returned from `GetWeaponCategory()` from the primary/secondary weapon's item state, but rarely both. I request that certain functions check the value of `XCGS_Item`'s `GetWeaponCategory()` as well so that custom game states can override the value of `WeaponCat` as needed.

This should allow `WeaponCat` weapon category switching on demand, although game balance will break.

Relevant code that requires slight changes:
X2SoldierClassTemplate.uc::IsWeaponAllowedByClass()::L141
```
	for (i = 0; i < AllowedWeapons.Length; ++i)
	{
		if (WeaponTemplate.InventorySlot == AllowedWeapons[i].SlotType &&
			WeaponTemplate.WeaponCat == AllowedWeapons[i].WeaponType)
			return true;
	}
```
X2BreakthroughCondition_WeaponType.uc::MeetsCondition():L31
```
	return WeaponTemplate.WeaponCat == WeaponTypeMatch;
```

X2Condition_UnitInventory::CallMeetsCondition()::L21
```
	if (ExcludeWeaponCategory != '')
	{		
		if (WeaponTemplate != none && WeaponTemplate.WeaponCat == ExcludeWeaponCategory)
			return 'AA_WeaponIncompatible';
	}
	if (RequireWeaponCategory != '')
	{
		if (RelevantItem == none || X2WeaponTemplate(RelevantItem.GetMyTemplate()).WeaponCat != RequireWeaponCategory)
			return 'AA_WeaponIncompatible';
	}
```

**Comment by Iridar** [comment] 2023-09-29 09:42
The problem is that you can't enforce mods doing this, which means it will potentially behave inconsistently. `GetWeaponCategory()` exists as a shortcut for convenience, not the only source of truth regarding a weapon's weapon category.

Custom Item States are also not possible without hacks due to existing code doing things [like this](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/1274c4a21fe549c29d33f38420a29639859e51e0/X2WOTCCommunityHighlander/Src/XComGame/Classes/XComGameState_HeadquartersXCom.uc#L4368), and even if this was changed, we still couldn't enforce mods doing it.

**Comment by E3245** [comment] 2023-09-29 23:34
I was worried that this isn't possible due to constraints in the existing code. 

On another note, if we can't adhere mods to new behavior, I'm wondering if there would be a way to allow item states or item templates to enlist themselves for custom creation code for those that need it?

**Comment by Iridar** [comment] 2023-09-30 04:15
Normally classes that extend `X2DataTemplate` can override `CreateInstanceFromTemplate()` to allow for custom state object classes, but since not all code even in vanilla game uses `CreateInstanceFromTemplate()` for items, it's not possible in this case.

**Comment by Iridar** [comment] 2023-10-28 18:06
Closing due to unfeasibility of either requests.

**Closed by Iridar** 2023-10-28 18:06 UTC
